import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopDeal from "./components/TopDeal";
import Header from "./components/Header";
import HeroSec from "./components/HeroSec";
import FeatureHeader from "./components/FeatureHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* {children} */}
        <TopDeal />
        <Header />
        <HeroSec />
        <FeatureHeader/>
      </body>
    </html>
  );
}
